version: '3.8'

services:
  postgres-dev:
    image: postgres:17.4
    container_name: postgres-dev
    environment:
      POSTGRES_DB: first_aid_kit_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # port hosta 5433 -> kontenerowy 5432
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-dev-data: