server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/first_aid_kit_dev
    username: postgres
    password: postgres

  mail:
    username: djdefkon@gmail.com
    password: ujfx czjr mhfk uswk

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT secret for local development only - NEVER use in production!
app:
  jwt:
    secret: LocalDevSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForLocalDev