spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/first_aid_kit
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres:5432/first_aid_kit
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  port: 8081

# Disable Swagger/OpenAPI in production
  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false

    # Disable rate limiting requests count increase for production
app:
  rate-limit:
    requests-per-minute: 10
